language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - mypy .
  - pytest --cov=api --no-cov-on-fail --cov-fail-under=55 api

after_success:
  - bash <(curl -s https://codecov.io/bash)